sudo: required
services:
  - docker

before_install:
  - docker build -t vcc-software/docker-react -f Dockerfile.dev . 

script:
  -  docker run -e CI=true vcc-software/docker-react npm run test
  # https://stackoverflow.com/questions/55991641/npm-test-coverage-never-exits
